import type { EditRecipe } from "./types"
import { RECIPE_VERSION } from "./types"

export const SPEED_STEPS = [0.25, 0.5, 0.75, 1, 1.25, 1.5, 2, 4] as const;

export const DEFAULT_RECIPE: EditRecipe = {
  preset: "vertical-9-16",
  customWidth: 1920,
  customHeight: 1080,
  framing: "fit",
  transitionId: "cross-dissolve",
  transitionDuration: 1,
  transitionPlacement: "both",
  trimStart: 0,
  trimEnd: null,
  rotate: 0,
  keepAudio: true,
  speed: 1,
  quality: 23,
  format: "mp4",
  brightness: 0,
  contrast: 1,
  saturation: 1,
  stabilization: false,
  soundOnCompletion: false,
  hueRotate: 0,
  sepia: 0,
  grayscale: 0,
  blur: 0,
  opacity: 1,
  invert: false,
  sharpen: 0,
  noise: 0,
  vignette: 0,
  colorBalanceR: 1,
  colorBalanceG: 1,
  colorBalanceB: 1,
  flipH: false,
  flipV: false,
  volume: 1,
  normalizeAudio: false,
  version: RECIPE_VERSION,
  watermarkEnabled: false,
  panX: 0,
  panY: 0,
  watermarkText: "",
  watermarkPosition: "bottom-right",
  watermarkSize: 24,
  watermarkOpacity: 70,
  watermarkColor: "#ffffff",
  watermarkFont: "Arial",
  captionEnabled: false,
  captionText: "Double-click to edit subtitles",
  captionFont: "Inter",
  captionSize: 28,
  captionColor: "#ffffff",
  captionStyle: "tiktok",
  captionPosition: "bottom-center",
  captionStartTime: 0,
  captionEndTime: null,
  audioFadeIn: 0,
  audioFadeOut: 0,
  audioEqualizer: "none",
};